### PR TITLE
Add translation for Ukrainian language

### PR DESCRIPTION
**Pull request by ErdtR**
Related to issue #2

### CODE REVIEW

**Comment by ErdtR** [comment]
@RockyTV can you check this?

**Review by Xinayder — CHANGES_REQUESTED** [review]
The locale tag for Ukrainian is `uk_UA`. Please change.

**Comment by ErdtR** [comment]
@RockyTV I've renamed the folder.

**Review by Xinayder — APPROVED** [review]

**Comment by Xinayder** [comment]
Thank you!

**Pull request merged**
